######################################################################
# Automatically generated by qmake (2.01a) Sun May 29 15:29:50 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += opengl

# Input
HEADERS += KVOViewerWidget.h
SOURCES += KVOViewerWidget.cpp main.cpp
